[search]
metric = "RMSE"
num_cpus = 2
max_points = 30

[space.scorer]
damping.user = { type = "float", min = 0.1, max = 100, scale = "log" }
damping.item = { type = "float", min = 0.1, max = 100, scale = "log" }

[pipeline]
file = "pipeline.toml"
